name: build book
description: build book
inputs:
  config:
    description: config file
    required: true
    default: config.yml
  working-directory:
    description: working directory
    default: .
runs:
  using: composite
  steps:
    - run: |
        CLEAN_PATH=$(readlink -f "${{ github.action_path }}")
        echo "CLEAN_ACTION_PATH=$CLEAN_PATH" >> $GITHUB_ENV
      shell: bash
    - run: cp -r "$CLEAN_ACTION_PATH/shares/." "${{ inputs.working-directory }}/"
      shell: bash
    - uses: ruby/setup-ruby@d697be2f83c6234b20877c3b5eac7a7f342f0d0c # v1.269.0
      with:
        bundler-cache: true
        working-directory: ${{ inputs.working-directory }}
    - run: echo "REVIEW_VERSION=`bundle info review --version | cut -d '.' -f 1-2`" >> $GITHUB_ENV
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - uses: masarakki/docker-alias@727b270d8133ccc1b5bcaf4b4064cfd7bf357553 # v3
      with:
        image: vvakame/review:${{ env.REVIEW_VERSION }}
        commands: review-pdfmaker
    - run: rm `bundle exec which review-pdfmaker`
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - run: bundle exec rake pdf
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        REVIEW_CONFIG_FILE: ${{ inputs.config }}
