name: build book
description: build book
inputs:
  config:
    description: config file
    required: true
    default: config.yml
  working-directory:
    description: working directory
    default: .
runs:
  using: composite
  steps:
    - run: |
        CLEAN_PATH=$(readlink -f "${{ github.action_path }}")
        echo "CLEAN_ACTION_PATH=$CLEAN_PATH" >> $GITHUB_ENV
      shell: bash
    - run: cp -r "$CLEAN_ACTION_PATH/shares/." "${{ inputs.working-directory }}/"
      shell: bash
    - uses: ruby/setup-ruby@b90be12699fdfcbee4440c2bba85f6f460446bb0 # v1.279.0
      with:
        bundler-cache: true
        working-directory: ${{ inputs.working-directory }}
    - run: bundle exec rake convert_md
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - run: |
        sed -i '1i inherit: ["config.common.yml"]' config.yml
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - run: docker run --rm -v `pwd`:/work vvakame/review:5.9 /bin/sh -c "cd /work && review-pdfmaker config.yml"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
